conky.config = {
    alignment = 'bottom_right',
    background = false,
    border_width = 0,
    cpu_avg_samples = 2,
    default_color = 'white',
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = false,
    draw_outline = false,
    draw_shades = true,
    default_shade_color = '000000',
    use_xft = true,
    font = 'Inter:size=10',
    gap_x = 50,
    gap_y = 50,
    minimum_height = 220,
    minimum_width = 300,
    maximum_width = 300,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_wayland = true,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'override',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    update_interval = 1.0,
    uppercase = true,
    
    color1 = 'FFFFFF',
    color2 = 'E4E4E7',
    color3 = 'D8E3E6',
}

conky.text = [[
${alignr 20}${color1}${font Inter Display:style=Black:size=56}${time %H}${color3}:${color1}${font Inter Display:style=Thin:size=56}${time %M}${font}
${voffset 2}${alignr 20}${color2}${font Inter Display:style=Medium:size=11}${time %A, %B %d}${font}
${voffset 20}${alignr 20}${color3}${font JetBrainsMono Nerd Font:style=Bold:size=14}  ${font}${color1}${font Inter:style=Bold:size=11}${cpu}%${font}   ${color3}${font JetBrainsMono Nerd Font:style=Bold:size=14}  ${font}${color1}${font Inter:style=Bold:size=11}${memperc}%${font}   ${color3}${font JetBrainsMono Nerd Font:style=Bold:size=14}   ${font}${color1}${font Inter:style=Bold:size=11}${battery_percent}%${font}
]]
