conky.config = {
    alignment = 'bottom_right',
    background = false,
    border_width = 0,
    cpu_avg_samples = 2,
    default_color = 'white',
    default_outline_color = 'white',
    default_shade_color = 'black',
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = false,
    draw_outline = false,
    draw_shades = false,
    use_xft = true,
    font = 'CaskaydiaCove Nerd Font:size=10',
    gap_x = 30,
    gap_y = 30,
    minimum_height = 450,
    minimum_width = 120,
    maximum_width = 120,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_stderr = false,
    out_to_wayland = true,
    extra_newline = false,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'override',
    own_window_transparent = false,
    own_window_argb_visual = true,
    own_window_argb_value = 160,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_colour = '09090B',
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = true,
    use_spacer = 'none',
    show_graph_scale = false,
    show_graph_range = false,
    
    color1 = 'FFFFFF', -- White
    color2 = 'F43F5E', -- Rose
    color3 = 'D8E3E6', -- Cyan
    color4 = '3F3F46', -- Zinc 700
}

conky.text = [[
${voffset 20}${alignc}${color3}${font :size=16}┌──┐${font}
${voffset 10}${alignc}${color1}${font CaskaydiaCove Nerd Font:style=Bold:size=48}${time %H}${font}
${voffset -15}${alignc}${color3}${font CaskaydiaCove Nerd Font:style=Bold:size=48}${time %M}${font}
${voffset 10}${alignc}${color4}${font :size=10}——————${font}
${voffset 10}${alignc}${color2}${font CaskaydiaCove Nerd Font:style=Bold:size=11}${time %a}${font}
${alignc}${color1}${font CaskaydiaCove Nerd Font:style=Bold:size=14}${time %d}${font}
${alignc}${color2}${font CaskaydiaCove Nerd Font:style=Bold:size=11}${time %b}${font}
${voffset 15}${alignc}${color4}${font :size=10}——————${font}
${voffset 15}${alignc}${font CaskaydiaCove Nerd Font:style=Bold:size=9}${color3}CPU${font}
${alignc}${color1}${cpu}%${font}
${voffset 10}${alignc}${font CaskaydiaCove Nerd Font:style=Bold:size=9}${color3}MEM${font}
${alignc}${color1}${memperc}%${font}
${voffset 10}${alignc}${font CaskaydiaCove Nerd Font:style=Bold:size=9}${color3}BAT${font}
${alignc}${color1}${battery_percent}%${font}
${voffset 15}${alignc}${color4}${font :size=10}——————${font}
${voffset 15}${alignc}${font CaskaydiaCove Nerd Font:style=Bold:size=10}${color1}${execi 1800 curl -s 'wttr.in/?format=%t' | sed 's/+//'}${font}
${voffset 15}${alignc}${color3}${font :size=16}└──┘${font}${voffset 20}
]]
